
trigger:
- master

pr:
- '*'

jobs:
- job: JobName
  pool:
    name: Default  # You can specify the agent pool (Default, MyAgentPool, etc.) if needed
  demands:
    - Agent.Name -equals Hosted Agent  # Replace YourAgentName with
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install and Build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'webapp'  # Replace with your Azure Service Connection name
    appType: 'webApp'
    appName: 'nodejshelloworld123'  # Replace with your Azure App Service Name
    package: '$(Pipeline.Workspace)/drop/app.zip'
